# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f2093c70f9677f359a77dcf5a85620f69b4fccf32f2c19d45111bcf5cb65863e3096b54c20ffdaf6da420e70665d638ca15c42f4e9ad305df1314edc2b57186

test:
  secret_key_base: 4d2f1c49a9e71fd030b9fef0b9058656989db0455de15adb7da1fa5f1dbb2179872506c400ed23a3d9d4a6bfbed4bd37e2b55ea8452b420e30f4d17330df0772

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
